import Navbar from "@/components/sections/Navbar";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>
          {children}
          <ToastContainer position="top-right" autoClose={3000} />
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
